config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create, :new, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  authenticated do
    root to: 'users#show', as: :authenticated_root
  end

  root to: 'home#index'

  #root to: "users#show"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  LIFETIME_IN_SECS = 7.days

  def self.delete_expired
    where(
      "created_at <= ?",
      Time.now - LIFETIME_IN_SECS
    ).destroy_all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    # p self.method(:authenticate_user!).source_location
    # render :index, layout: "application"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @user = current_user
    @item = Item.new
  end

  def create
    @user = current_user
    @item = @user.items.build(item_params)

    if @item.save
      flash[:notice] = "Item was saved successfully."
      redirect_to [@user]
    else
      flash[:alert] = "There was an error saving the item."
      render :new
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    # @item = Item.find(params[:id])
    # if @item.user == current_user
    if @item.destroy
      flash[:notice] = "\"#{@item.name}\" was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the item."
    end

    respond_to do |format|
      format.html
      format.js
    end
    # end
  end



  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <div class="container">
    <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <% if item.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(item.errors.count, "error") %>.</h4>
      <ul>
        <% item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of your to-do item" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="media" id="item-<%= item.id %>">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to "", [@user, item], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
      <%= item.name %>
    </h4>
    <small>
      <%= distance_of_time_in_words(item.created_at, Time.now) %> since item was created.
    </small>
  </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger><button type='button' class='close' data-dismiss='alert>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/new.html.erb
<h1>New To-Do Item</h1>
<div class="row">
  <div class="col-md-12">
    <p>Make sure you stay on top of your to-dos!</p>
  </div>
</div>

<div class="col-md-8">
  <%= render partial: 'form', locals: { user: @user, item: @item } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="pull-right user-info">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h1>
  <%= @user.email %>
</h1>
<br>
<div class="container">
  <h3>To-Do Items:</h3>
  <%= render @user.items %>
  <%# @user.items.each do |item| %>
    <%#= render 'item', locals: { item: item } %>
  <%# end %>
</div>
<br>
<div class="container">
  <%= link_to "New Item", new_user_item_path(@user), class: 'btn btn-success' %>
</div>